"""Add description and avatar_url to pet_profiles

Revision ID: a1b2c3d4e5f6
Revises: e858b4650b66
Create Date: 2025-12-26 19:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'a2f90732dd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_profiles', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
