"""Restore PetProfile columns

Revision ID: e858b4650b66
Revises: f2b67b924f1a
Create Date: 2025-12-23 12:36:11.124160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e858b4650b66'
down_revision = 'f2b67b924f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('breed', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('adoption_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_profiles', schema=None) as batch_op:
        batch_op.drop_column('adoption_date')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('gender')
        batch_op.drop_column('breed')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
